/**
 * SimData Patching Infrastructure
 * Allows updating byte templates for Sims 4 binary data.
 */

interface SimDataPatchOptions {
  templateB64: string;
  tuningId: bigint;
  nameHash: number;
  tuningIdOffset: number;
  nameHashOffset: number;
}

/**
 * Decodes base64 template, patches TuningId (uint64) and nameHash (uint32), returns bytes.
 */
export function patchSimData(options: SimDataPatchOptions): Uint8Array {
  const binaryString = atob(options.templateB64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }

  const view = new DataView(bytes.buffer);

  // Patch TuningId (Tuning Instance ID) - uint64 LE
  const low = Number(options.tuningId & 0xFFFFFFFFn);
  const high = Number(options.tuningId >> 32n);
  view.setUint32(options.tuningIdOffset, low, true);
  view.setUint32(options.tuningIdOffset + 4, high, true);

  // Patch Name Hash (FNV32 of internal name) - uint32 LE
  view.setUint32(options.nameHashOffset, options.nameHash, true);

  return bytes;
}

/**
 * Real binary templates for Sims 4 SimData.
 * These are patched with the correct Tuning Instance ID and name hash at runtime.
 */
export const TEMPLATES = {
  TRAIT: {
    // b64 for TRAIT
    b64: "REFUQQEBAAAYAAAAAwAAABACAAABAAAAAAAAAAAAAABdBAAApzcRePgBAAANAAAAkAAAAMwAAAABAAAAAAAAgMWdHIEAAACACAAAAAgAAABAAQAADwAAAAAAAIDFnRyBAAAAgAEAAAABAAAApAEAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAAAAAIAAAAAAAAgAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAADoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADRAAAAAAAAgAAAAAAAAAAAgAAAAAIAAAD5BjZ4bITwMILYsgAAAAAAeAAAAAMAAACIAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAACAVTigwQEAAAAAAAAAAgAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEFjdGl2ZQAAAAAAAAAAAFcCAADH3V/LyITVU5AAAAAIAAAAEQAAAHkBAADlV4sFEwAAABgAAAAAAACAHwIAABJd9BgVAAAAiAAAAAAAAICuAQAAaWkFHhQAAABMAAAAAAAAgNMBAADTfR8eFAAAAHwAAAAAAACAcwEAADMXwzgOAAAARAAAAAAAAIB/AQAA7QtfZQ4AAABQAAAAAAAAgHMBAAB6k6puEwAAAFgAAAAAAACAIwEAALPIQngLAAAAQAAAAAAAAIDKAAAALrktkw4AAAAQAAAAAAAAgEkBAADw5secFAAAAHgAAAAAAACAYAEAAPoyYKEIAAAAgAAAAAAAAICuAAAAl0g1pwsAAAAoAAAAAAAAgGQAAAA1L+uvDgAAAAAAAAAAAACA9AAAAIYKI7gOAAAAcAAAAAAAAICFAAAA+HXruBMAAAAwAAAAAAAAgMQAAABR0q+6DgAAAGgAAAAAAACAGQAAAFt0Nd4OAAAACAAAAAAAAIBhZ2VzAGJiX2ZpbHRlcl9zdHlsZXMAYmJfZmlsdGVyX3RhZ3MAY2FzX2lkbGVfYXNtX3N0YXRlAGNhc19zZWxlY3RlZF9pY29uAGNhc190cmFpdF9hc21fcGFyYW0AY29uZmxpY3RpbmdfdHJhaXRzAGRpc3BsYXlfbmFtZQBnZW5kZXJzAGljb24Ac3BlY2llcwB0YWdzAHRyYWl0X2Rlc2NyaXB0aW9uAHRyYWl0X29yaWdpbl9kZXNjcmlwdGlvbgB0cmFpdF90eXBlAHVpX2NhdGVnb3J5AVRyYWl0AENvbnN0cnVjdG9yAA==",
    tuningIdOffset: 48,
    nameHashOffset: 36
  },
  BUFF: {
    // b64 for BUFF
    b64: "REFUQQEBAAAYAAAAAQAAAMAAAAABAAAACgAAAAAAAAD9AQAApzcReKgAAAANAAAAUAAAAEwAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABGxmTPFrn4ir7jBP0AAAAA6kZVohYy8zu+4wT9AAAAAAAAAAAAAAAA+QY2eGyE8DCC2LIAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAEgBAACW6BdgVilycVAAAAAIAAAACQAAAMcAAAB44fMaEwAAABAAAAAAAACA6QAAAC+jnBsSAAAAOAAAAAAAAIDQAAAAepOqbhMAAAAoAAAAAAAAgKEAAABJiwWRFAAAACAAAAAAAACAngAAAKxVLqIUAAAAJAAAAAAAAICjAAAAc3sltgYAAABAAAAAAAAAgJsAAADW38fAFAAAAEQAAAAAAACAlgAAAKfSPNsGAAAASAAAAAAAAIAUAAAAsWlw5hMAAAAAAAAAAAAAgGF1ZGlvX3N0aW5nX29uX2FkZABhdWRpb19zdGluZ19vbl9yZW1vdmUAYnVmZl9kZXNjcmlwdGlvbgBidWZmX25hbWUAaWNvbgBtb29kX3R5cGUAbW9vZF93ZWlnaHQAdGltZW91dF9zdHJpbmcAdWlfc29ydF9vcmRlcgBCdWZmAENvbnN0cnVjdG9yAA==",
    tuningIdOffset: 48,
    nameHashOffset: 36
  },
  CAREER: {
    // b64 for CAREER
    b64: "REFUQQEBAAAYAAAAAQAAAFAAAAABAAAAAAAAAAAAAADHAAAApzcReDgAAAANAAAAGAAAAAwAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAOtrmXPtm+Q2GAAAAAgAAAADAAAAPAAAANbw7HgIAAAAAAAAAAAAAIBIAAAAH42DjRIAAAAQAAAAAAAAgCQAAAAKqry8AAAAAAgAAAAAAACAY2FyZWVyX2NhdGVnb3J5AHNob3dfaWRlYWxfbW9vZABzdGFydF90cmFjawBDYXJlZXIAQ29uc3RydWN0b3IA",
    tuningIdOffset: 48,
    nameHashOffset: 36
  },
  ASPIRATIONTRACK: {
    // b64 for ASPIRATIONTRACK
    b64: "REFUQQEBAAAYAAAAAwAAACABAAACAAAAGQAAAAAAAAAFAwAApzcReAgBAAANAAAAWAAAAEwAAAABAAAAAAAAgMWdHIEEAQAADQAAABAAAACQAAAABAAAAAAAAIDFnRyBAAAAgAEAAAABAAAAtAAAAAEAAAAAAAAAAAAAAAAAAABgAAAABAAAAOqeAgAAAAAAdlS4r9qccKIhbAaubGQzNYLYsgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkAAAAAAAAgAAAAAAwnwIAAAAAACefAgAAAAAAAAAAAAAAAAABAAAAAAAAAO6eAgAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMMBAABqzV+YnAFEFVgAAAAgAAAACwAAAMUBAAB8X3dg3PkS0BAAAADkAAAAAgAAAF8BAADu+zQvCwAAADwAAAAAAACAagEAABzFGjgSAAAASAAAAAAAAIDxAAAAYV6VThQAAAAQAAAAAAAAgA4BAACHE/ROAAAAADgAAAAAAACA5wAAAHqTqm4TAAAAGAAAAAAAAIAoAQAAKJikbxIAAABQAAAAAAAAgMQAAAAKbE9wEwAAACgAAAAAAACA4gAAABdcRHEOAAAAQAAAAAAAAICKAAAANXswihQAAAAUAAAAAAAAgFAAAABc6vCLDgAAAAAAAAAAAACASAAAAOFfhqESAAAACAAAAAAAAIDLAAAA3GPtKBIAAAAIAAAAAAAAgLMAAACCLoRGCAAAAAAAAAAAAACAYXNwaXJhdGlvbnMAY2F0ZWdvcnkAZGVzY3JpcHRpb25fdGV4dABkaXNwbGF5X3RleHQAaWNvbgBpY29uX2hpZ2hfcmVzAGlzX2hpZGRlbl91bmxvY2thYmxlAG1vb2RfYXNtX3BhcmFtAG92ZXJyaWRlX3RyYWl0cwBwcmltYXJ5X3RyYWl0AHJld2FyZABBc3BpcmF0aW9uVHJhY2sAa2V5AHZhbHVlAEFzcGlyYXRpb25zTWFwcGluZ1R1cGxlAENvbnN0cnVjdG9yAA==",
    tuningIdOffset: 48,
    nameHashOffset: 36
  }
};
